version: 2
jobs:
  deploy:
    docker:
      - image: cimg/node:15.5.1
    steps:
      - checkout
      - run:
          name: check version
          command: node --version
      - run:
          name: npm install
          command: npm install
      - run:
          name: node/test
          command: npm run test
      - run:
          name: Installing deployment dependencies
          working_directory: /
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install python3-pip python3-dev build-essential
            sudo pip3 install awsebcli
      - run:
          name: checkEbversion
          command: eb --version
      - run:
          name: environmantVariables1
          command: echo $DATA_CSV

      - run:
          name: Deploying
          command: eb deploy $CIRCLE_BRANCH-devassign

workflows:
  version: 2
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - staging
                - master
